export const GEM_CAPABILITY_MATRIX = Object.freeze([
{id:'MINERAL_SYSTEMS',layer:'INTELLIGENCE',capability:'Mineral-systems prospectivity',sources:['Geoscience Australia Mineral Systems','USGS Earth MRI'],gem:['mineralSystemKnowledgeGraph','trueProspectivity','hierarchicalTargetEngine']},
{id:'GLOBAL_DEPOSITS',layer:'DATA',capability:'Global mines, deposits, occurrences and commodities',sources:['USGS mineral resources data','USGS MRDS','national geological surveys'],gem:['globalMineralSources','globalTargetEngine']},
{id:'GEOPHYSICS',layer:'EVIDENCE',capability:'Magnetic, radiometric, gravity and electromagnetic evidence',sources:['Earth MRI','NOAA/NCEI EMAG2v3','national airborne surveys'],gem:['trueProspectivity','evidenceFusion']},
{id:'GEOCHEMISTRY',layer:'EVIDENCE',capability:'Pathfinder and multi-element geochemistry',sources:['Geoscience Australia CMMI','national geochemical surveys'],gem:['geochemistry','trueProspectivity']},
{id:'HYPERSPECTRAL',layer:'EVIDENCE',capability:'Mineral and alteration spectral signatures',sources:['NASA EMIT','EnMAP','USGS hyperspectral programs','Sentinel-2'],gem:['earthObservationEvidence','emitSampler','trueProspectivity']},
{id:'TERRAIN_STRUCTURE',layer:'EVIDENCE',capability:'Topography, drainage and structural context',sources:['global DEMs','satellite-derived terrain','geological mapping'],gem:['trueProspectivity','mineralSystemKnowledgeGraph']},
{id:'MINE_ACTIVITY',layer:'CONTEXT',capability:'Existing mining and surface activity intelligence',sources:['Earthrise Mining Detector','public mining datasets'],gem:['earthriseMiningEvidence']},
{id:'3D_GEOLOGY',layer:'DECISION',capability:'Living 3D geological and drillhole model',sources:['industry-standard implicit and explicit modelling workflows'],gem:['drillIntelligence','mineralSystemKnowledgeGraph']},
{id:'DRILL_INTELLIGENCE',layer:'DECISION',capability:'Competing hypotheses and next-best drilling action',sources:['best-practice exploration workflows'],gem:['drillIntelligence','explorationOptimizer']},
{id:'RESOURCE_PLANNING',layer:'ASSET',capability:'Resource/block-model and mine-planning interoperability',sources:['industry-standard block modelling and mine planning workflows'],gem:['investmentIntelligence']},
{id:'COMMODITY_SUPPLY',layer:'MARKET',capability:'Global production, trade and strategic supply context',sources:['BGS World Mineral Statistics','USGS Mineral Commodity Summaries'],gem:['investmentIntelligence']},
{id:'MINE_WASTE',layer:'CIRCULAR',capability:'Mine-waste and tailings mineral potential',sources:['USGS Earth MRI mine-waste programs'],gem:['future mineWasteEngine']},
{id:'GOVERNANCE',layer:'TRUST',capability:'Provenance, reproducibility, auditability and security',sources:['enterprise data-governance patterns'],gem:['gemStateStore','gemRuntimePolicy']},
{id:'NATIONAL_MINERAL_SECURITY',layer:'GOVERNMENT',capability:'Country mineral security, trade exposure and supply-chain intelligence',sources:['USGS MCS','IEA Critical Minerals Data Explorer','IEA Policy Tracker','UNCTADstat','World Bank Commodity Markets','national official datasets'],gem:['governmentMineralIntelligence','investmentIntelligence','gemStateStore']},
{id:'MINERAL_SECURITY_INDEX',layer:'GOVERNMENT',capability:'Transparent country × mineral vulnerability and resilience indicators',sources:['USGS','IEA','UNCTAD','World Bank','national official datasets'],gem:['mineralSecurityIndex','governmentMineralIntelligence']},
{id:'GLOBAL_DATA_INGESTION',layer:'DATA',capability:'Versioned ingestion and provenance for official mineral statistics',sources:['USGS MCS','USGS Minerals Yearbook','IEA','UNCTAD','World Bank'],gem:['globalMineralDataIngestion','gemStateStore']},
{id:'SUPPLY_CHAIN_GRAPH',layer:'MARKET',capability:'Global mine-to-processing-to-manufacturing dependency graph',sources:['USGS','IEA','UNCTAD','national official datasets'],gem:['globalSupplyChainGraph','mineralSecurityIndex']},
{id:'GLOBAL_MINERAL_KNOWLEDGE_GRAPH',layer:'INTELLIGENCE',capability:'Cross-domain graph linking countries, minerals, mines, processing, trade and applications',sources:['USGS','IEA','UNCTAD','national geological and statistical surveys'],gem:['globalMineralKnowledgeGraph','globalSupplyChainGraph','governmentMineralIntelligence']},
{id:'GLOBAL_SUPPLIER_NETWORK',layer:'MARKET',capability:'Verified supplier network across minerals, metals, precious metals and petroleum',sources:['USGS','IEA oil data','national mineral and petroleum agencies','official company disclosures'],gem:['globalSupplierRegistry','globalMineralKnowledgeGraph','globalSupplyChainGraph']},
{id:'SUPPLIER_DISCOVERY',layer:'MARKET',capability:'Ranked supplier discovery, verification and commodity coverage analysis',sources:['official statistical agencies','national regulators','official company disclosures'],gem:['supplierDiscoveryEngine','globalSupplierRegistry','globalSupplyChainGraph']}
]);
export function getGemCapabilities(){return GEM_CAPABILITY_MATRIX.map(e=>({...e,sources:[...e.sources],gem:[...e.gem]}));}
export function summarizeGemCapabilities(){const layers={};for(const e of GEM_CAPABILITY_MATRIX)layers[e.layer]=(layers[e.layer]||0)+1;return Object.freeze({capabilityCount:GEM_CAPABILITY_MATRIX.length,layers:Object.freeze(layers),strategicCommodities:['gold','silver','platinum','palladium','rhodium','iridium','copper','lithium','nickel','cobalt','graphite','manganese','rare earth elements','tungsten','tin','niobium','tantalum','vanadium','uranium','chromium','zinc','lead']});}