/**
 * GEM Government Mineral Security Intelligence.
 *
 * Policy-neutral intelligence layer: facts, indicators and scenarios are
 * separated from GEM prospectivity inference. No political recommendation
 * is generated by this module.
 */
export const GEM_GOVERNMENT_INTELLIGENCE_VERSION = '1.0.0';

export const GOVERNMENT_DATA_DOMAINS = Object.freeze([
  { id:'GEOLOGY', title:'Geology & mineral endowment', sources:['USGS','Geoscience Australia','national geological surveys'] },
  { id:'PRODUCTION', title:'Mine and refinery production', sources:['USGS MCS','BGS','national statistics'] },
  { id:'RESERVES_RESOURCES', title:'Published reserves and resources', sources:['USGS','national geological surveys','public technical reports'] },
  { id:'TRADE', title:'Bilateral mineral trade', sources:['UNCTADstat','UN Comtrade'] },
  { id:'DEMAND', title:'Demand and technology scenarios', sources:['IEA Critical Minerals Data Explorer'] },
  { id:'PRICES', title:'Commodity prices and forecasts', sources:['World Bank Commodity Markets','public exchanges'] },
  { id:'POLICY', title:'Mineral policies, regulations and restrictions', sources:['IEA Critical Minerals Policy Tracker','official government gazettes'] },
  { id:'SUPPLY_CHAIN', title:'Mining, refining and processing concentration', sources:['IEA','UNCTAD','USGS'] },
  { id:'INFRASTRUCTURE', title:'Ports, rail, roads, power and processing infrastructure', sources:['OpenStreetMap','national infrastructure datasets','public satellite data'] },
  { id:'WATER_ENERGY', title:'Water and energy constraints', sources:['global hydrography','national water datasets','global power datasets'] },
  { id:'ENVIRONMENT', title:'Environmental and land-use constraints', sources:['ESA WorldCover','protected-area datasets','national environmental agencies'] },
  { id:'PROJECTS', title:'Projects, mines, plants and development pipeline', sources:['public company disclosures','government mining registries'] },
  { id:'RECYCLING', title:'Recycling and secondary supply', sources:['IEA','UNCTAD','national statistics'] },
  { id:'SECURITY', title:'Supply disruption exposure and concentration', sources:['IEA','UNCTAD','GEM derived indicators'] }
]);

export const STRATEGIC_COUNTRY_INDICATORS = Object.freeze([
  'domestic_supply_coverage',
  'import_dependence',
  'export_concentration',
  'processing_concentration',
  'trade_exposure',
  'project_pipeline',
  'geological_potential',
  'infrastructure_readiness',
  'water_constraint',
  'energy_constraint',
  'environmental_constraint',
  'recycling_potential',
  'policy_coverage',
  'data_confidence'
]);

function finite(value){return Number.isFinite(Number(value));}

export function buildCountryMineralProfile(input = {}) {
  const country = String(input.country || '').trim();
  const mineral = String(input.mineral || '').trim().toLowerCase();
  if (!country || !mineral) throw new TypeError('country and mineral are required');

  const indicators = {};
  for (const key of STRATEGIC_COUNTRY_INDICATORS) {
    if (finite(input.indicators?.[key])) indicators[key] = Number(input.indicators[key]);
  }

  return Object.freeze({
    version:GEM_GOVERNMENT_INTELLIGENCE_VERSION,
    country,
    mineral,
    generatedAt:input.generatedAt || new Date().toISOString(),
    indicators:Object.freeze(indicators),
    facts:Array.isArray(input.facts) ? input.facts.map(f=>({...f})) : [],
    sources:Array.isArray(input.sources) ? input.sources.map(s=>({...s})) : [],
    dataGaps:Array.isArray(input.dataGaps) ? [...input.dataGaps] : [],
    provenanceRequired:true
  });
}

export function buildSupplyRiskSignals(profile) {
  const i = profile?.indicators || {};
  const signals = [];
  if (finite(i.import_dependence) && i.import_dependence >= 0.75) signals.push('HIGH_IMPORT_DEPENDENCE');
  if (finite(i.processing_concentration) && i.processing_concentration >= 0.75) signals.push('HIGH_PROCESSING_CONCENTRATION');
  if (finite(i.export_concentration) && i.export_concentration >= 0.75) signals.push('HIGH_EXPORT_CONCENTRATION');
  if (finite(i.water_constraint) && i.water_constraint >= 0.75) signals.push('WATER_CONSTRAINT');
  if (finite(i.energy_constraint) && i.energy_constraint >= 0.75) signals.push('ENERGY_CONSTRAINT');
  return Object.freeze({country:profile.country,mineral:profile.mineral,signals});
}
